[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
svm_greet = "97uCKFPMDU4S4DQmNwu7BQAYCCFM5fMBms7zk71uJeib"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
